-- H2 2.4.240;
;             
CREATE USER IF NOT EXISTS "SA" SALT 'c91ef5baf4dbbf53' HASH '8d69770c7f1964af5b3b2ea2ffec45612378571f227e8f874f7696187ab8da39' ADMIN;         
CREATE CACHED TABLE "PUBLIC"."CLAIM"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 120) NOT NULL,
    "BANK_ACCOUNT_NUMBER" CHARACTER VARYING(255),
    "BANK_IFSC_CODE" CHARACTER VARYING(255),
    "CLAIM_AMOUNT" NUMERIC(38, 2),
    "CLAIM_DESCRIPTION" CHARACTER VARYING(2000),
    "FILED_AT" TIMESTAMP(6),
    "INVESTIGATION_NOTES" CHARACTER VARYING(2000),
    "POLICE_REPORT_FILED" BOOLEAN,
    "POLICE_REPORT_NUMBER" CHARACTER VARYING(255),
    "REJECTION_REASON" CHARACTER VARYING(255),
    "REVIEWED_AT" TIMESTAMP(6),
    "SETTLEMENT_AMOUNT" NUMERIC(38, 2),
    "STATUS" ENUM('APPROVED', 'PENDING', 'REJECTED', 'SETTLED', 'UNDER_INVESTIGATION'),
    "ASSIGNED_OFFICER_USER_ID" BIGINT,
    "CUSTOMER_USER_ID" BIGINT,
    "INCIDENT_ID" BIGINT,
    "REVIEWED_BY_USER_ID" BIGINT
); 
ALTER TABLE "PUBLIC"."CLAIM" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_3" PRIMARY KEY("ID");        
-- 10 +/- SELECT COUNT(*) FROM PUBLIC.CLAIM;  
INSERT INTO "PUBLIC"."CLAIM" VALUES
(1, '9876543210001234', 'HDFC0001234', 200000.00, 'Requesting partial coverage for server restoration and security audit post-ransomware.', TIMESTAMP '2026-03-06 14:18:51.387744', '', TRUE, 'CYB-2026-100', NULL, TIMESTAMP '2026-03-11 11:23:49.006451', 150000.00, 'SETTLED', 8, 2, 1, 8),
(2, '1234567890009876', 'SBIN0005432', 450000.00, 'Data breach caused significant remediation cost including patient notification and legal fees.', TIMESTAMP '2026-02-10 14:18:51.394471', 'API misconfiguration confirmed via forensic analysis. Settlement of Rs.4,00,000 approved after applicable deductible and policy review. Payout authorized to registered bank account.', FALSE, NULL, NULL, TIMESTAMP '2026-02-18 14:18:51.394471', 400000.00, 'SETTLED', 9, 3, 2, 9),
(3, '1234567890009876', 'SBIN0005432', 160000.00, 'Phishing attack compromised VPN credentials. Requesting coverage for lost business and system audit.', TIMESTAMP '2026-03-06 14:18:51.401177', '', TRUE, 'CYB-2026-200', NULL, TIMESTAMP '2026-03-11 11:20:09.156675', 105000.00, 'SETTLED', 9, 3, 3, 8),
(4, '7654321009875432', 'ICIC0009876', 750000.00, 'Reimbursement for fraudulent wire transfer. Bank recovery unsuccessful.', TIMESTAMP '2026-03-03 14:18:51.437433', '', TRUE, 'CYB-2026-300', NULL, TIMESTAMP '2026-03-11 01:07:18.214215', 750000.00, 'SETTLED', 8, 4, 4, 8),
(5, '9876543210001234', 'HDFC0001234', 300000.00, 'Secondary claim for business interruption losses due to server downtime.', TIMESTAMP '2026-02-23 14:18:51.442003', NULL, FALSE, NULL, 'Claim rejected: System was unpatched for 9 months, violating minimum security hygiene clause in Section 4.2 of the policy agreement.', TIMESTAMP '2026-02-26 14:18:51.442003', NULL, 'REJECTED', 9, 2, 1, 9),
(33, '284571052988', 'SBIN200345', 200000.00, 'Data got leaked', TIMESTAMP '2026-03-11 01:04:38.124429', '', FALSE, '', NULL, TIMESTAMP '2026-03-11 01:06:52.613275', 176600.00, 'SETTLED', 8, 2, 33, 8),
(65, '284571052988', 'HDFC125028', 5000000.00, 'The insider threat incident caused unauthorized access to sensitive data and disruption of internal systems. The requested claim amount covers costs related to incident response, forensic investigation, system recovery, and security improvements required to mitigate the impact of the breach.', TIMESTAMP '2026-03-11 12:17:34.770759', '', FALSE, '', NULL, TIMESTAMP '2026-03-13 12:06:44.120745', NULL, 'UNDER_INVESTIGATION', 8, 2, 65, 8),
(66, '284571052988', 'HDFCV10280', 18000000.00, U&'File a claim\000a', TIMESTAMP '2026-03-11 12:47:21.037828', '', FALSE, '', NULL, TIMESTAMP '2026-03-11 13:10:13.997533', 17961000.00, 'SETTLED', 8, 2, 66, 8),
(111, 'SBIN202057', 'SBIN4004', 200000.00, 'Claim Requested', TIMESTAMP '2026-03-13 06:13:13.22078', NULL, FALSE, '', 'no supporting documents and fraud risk score is also high', TIMESTAMP '2026-03-13 06:15:01.121249', NULL, 'REJECTED', 8, 2, 111, 8),
(112, 'SBIN2005', 'HDFSC2005', 1000000.00, 'nothing', TIMESTAMP '2026-03-13 12:05:21.186898', NULL, TRUE, 'CY22005', NULL, NULL, NULL, 'PENDING', 8, 2, 112, NULL);       
CREATE CACHED TABLE "PUBLIC"."CYBER_POLICIES"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 139) NOT NULL,
    "BASE_PREMIUM" NUMERIC(38, 2) NOT NULL,
    "COVERAGE_LIMIT" NUMERIC(38, 2) NOT NULL,
    "CREATED_AT" TIMESTAMP(6),
    "DESCRIPTION" CHARACTER VARYING,
    "DURATION_MONTHS" INTEGER NOT NULL,
    "IS_ACTIVE" BOOLEAN,
    "POLICY_NAME" CHARACTER VARYING(255) NOT NULL,
    "SECTOR" CHARACTER VARYING(255) NOT NULL
);          
ALTER TABLE "PUBLIC"."CYBER_POLICIES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_B" PRIMARY KEY("ID");               
-- 43 +/- SELECT COUNT(*) FROM PUBLIC.CYBER_POLICIES;         
INSERT INTO "PUBLIC"."CYBER_POLICIES" VALUES
(1, 250000.00, 500000000.00, TIMESTAMP '2026-03-10 14:18:50.403789', 'Comprehensive cyber insurance for the banking sector protecting financial data.', 12, TRUE, 'Financial Data Protection Plan', 'Banking'),
(2, 180000.00, 300000000.00, TIMESTAMP '2026-03-10 14:18:50.403789', 'Protection for ATM networks against malware and fraud.', 12, TRUE, 'ATM Network Security Plan', 'Banking'),
(3, 300000.00, 750000000.00, TIMESTAMP '2026-03-10 14:18:50.405306', 'Protection for digital payment gateways and platforms.', 12, TRUE, 'Digital Payment Security Plan', 'Banking'),
(4, 500000.00, 1000000000.00, TIMESTAMP '2026-03-10 14:18:50.405306', 'Total coverage for core banking infrastructure.', 12, TRUE, 'Core Banking System Shield', 'Banking'),
(5, 200000.00, 400000000.00, TIMESTAMP '2026-03-10 14:18:50.405306', 'Protects high-net-worth client investment data.', 12, TRUE, 'Investment Data Privacy', 'Banking'),
(6, 120000.00, 200000000.00, TIMESTAMP '2026-03-10 14:18:50.405306', 'Ensures patient records are protected from medical data breaches.', 12, TRUE, 'Patient Data Protection Policy', 'Healthcare'),
(7, 90000.00, 150000000.00, TIMESTAMP '2026-03-10 14:18:50.405306', 'Protects telehealth sessions and remote patient monitoring.', 12, TRUE, 'Telemedicine Security Plan', 'Healthcare'),
(8, 150000.00, 300000000.00, TIMESTAMP '2026-03-10 14:18:50.405306', 'Protection for connected medical devices.', 12, TRUE, 'Medical IoT Shield', 'Healthcare'),
(9, 350000.00, 800000000.00, TIMESTAMP '2026-03-10 14:18:50.405545', 'Prevents hospital shutdown due to ransomware attacks.', 12, TRUE, 'Hospital Ransomware Defense', 'Healthcare'),
(10, 80000.00, 100000000.00, TIMESTAMP '2026-03-10 14:18:50.405545', 'Protects prescription records and pharmacy databases.', 12, TRUE, 'Pharmacy Data Security', 'Healthcare'),
(11, 80000.00, 100000000.00, TIMESTAMP '2026-03-10 14:18:50.405545', 'Protects online stores from payment fraud and customer data theft.', 12, TRUE, 'Online Retail Security Plan', 'E-commerce'),
(12, 110000.00, 200000000.00, TIMESTAMP '2026-03-10 14:18:50.405545', 'Covers losses due to website downtime from DDoS attacks.', 12, TRUE, 'E-commerce DDoS Protection', 'E-commerce'),
(13, 150000.00, 300000000.00, TIMESTAMP '2026-03-10 14:18:50.405545', 'Protects against breaches originating from third-party vendors.', 12, TRUE, 'Supply Chain Cyber Security', 'E-commerce'),
(14, 60000.00, 80000000.00, TIMESTAMP '2026-03-10 14:18:50.405545', 'Protects against credential stuffing and account takeovers.', 12, TRUE, 'Customer Account Shield', 'E-commerce'),
(15, 95000.00, 150000000.00, TIMESTAMP '2026-03-10 14:18:50.405545', 'Specific coverage for mobile app shopping platforms.', 12, TRUE, 'Mobile Commerce Protection', 'E-commerce'),
(16, 200000.00, 400000000.00, TIMESTAMP '2026-03-10 14:18:50.406328', 'Coverage for IT and SaaS companies against software failure liability.', 12, TRUE, 'Software Liability Protection', 'IT / SaaS'),
(17, 250000.00, 500000000.00, TIMESTAMP '2026-03-10 14:18:50.406328', 'Covers the cost of cloud outages affecting clients.', 12, TRUE, 'Cloud Service Interruption Plan', 'IT / SaaS'),
(18, 180000.00, 350000000.00, TIMESTAMP '2026-03-10 14:18:50.406328', 'Protects against zero-day exploits and poor code security.', 12, TRUE, 'Code Vulnerability Defense', 'IT / SaaS'),
(19, 300000.00, 600000000.00, TIMESTAMP '2026-03-10 14:18:50.407888', 'Comprehensive coverage for MSPs handling multiple clients.', 12, TRUE, 'Managed Service Provider Shield', 'IT / SaaS'),
(20, 400000.00, 800000000.00, TIMESTAMP '2026-03-10 14:18:50.408878', 'Protection for AI models against data poisoning and theft.', 12, TRUE, 'AI / Machine Learning Security', 'IT / SaaS'),
(21, 120000.00, 200000000.00, TIMESTAMP '2026-03-10 14:18:50.408979', 'Protects industrial systems from production risks.', 12, TRUE, 'Industrial Control System Protection', 'Manufacturing'),
(22, 180000.00, 350000000.00, TIMESTAMP '2026-03-10 14:18:50.408979', 'Coverage for halt in manufacturing due to cyber attacks on suppliers.', 12, TRUE, 'Supply Chain Disruption Plan', 'Manufacturing');            
INSERT INTO "PUBLIC"."CYBER_POLICIES" VALUES
(23, 250000.00, 500000000.00, TIMESTAMP '2026-03-10 14:18:50.408979', 'Protects proprietary designs and manufacturing formulas.', 12, TRUE, 'Intellectual Property Theft', 'Manufacturing'),
(24, 150000.00, 300000000.00, TIMESTAMP '2026-03-10 14:18:50.408979', 'Secures robotic arms and automated factory equipment.', 12, TRUE, 'Automated Assembly Line Security', 'Manufacturing'),
(25, 130000.00, 250000000.00, TIMESTAMP '2026-03-10 14:18:50.408979', 'Protects IIoT sensors and smart factory networks.', 12, TRUE, 'Smart Factory IoT Shield', 'Manufacturing'),
(26, 70000.00, 100000000.00, TIMESTAMP '2026-03-10 14:18:50.408979', 'Protects student records and administrative databases.', 12, TRUE, 'Student Data Privacy Plan', 'Education'),
(27, 100000.00, 200000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Secures open campus networks against widespread threats.', 12, TRUE, 'Campus Network Security', 'Education'),
(28, 85000.00, 150000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Protects virtual classrooms and online testing systems.', 12, TRUE, 'Online Learning Platform Shield', 'Education'),
(29, 150000.00, 300000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Secures valuable university research and intellectual property.', 12, TRUE, 'Research Data Protection', 'Education'),
(30, 120000.00, 250000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Protects tuition payment portals and university funds.', 12, TRUE, 'University Financial Cyber Protection', 'Education'),
(31, 300000.00, 1000000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Secures sensitive citizen databases and public records.', 12, TRUE, 'Citizen Data Protection', 'Government'),
(32, 500000.00, 2000000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Protects power grids, water supplies, and public transit.', 12, TRUE, 'Critical Infrastructure Shield', 'Government'),
(33, 200000.00, 500000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Secures online government portals and tax systems.', 12, TRUE, 'E-Governance Security Plan', 'Government'),
(34, 800000.00, 3000000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Top-tier protection for classified government data.', 12, TRUE, 'Defense & Intelligence Data Security', 'Government'),
(35, 150000.00, 300000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Protects towns and cities from being held hostage by ransomware.', 12, TRUE, 'Local Municipality Ransomware Defense', 'Government'),
(36, 180000.00, 400000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Covers losses from broadcast signal hacking or downtime.', 12, TRUE, 'Broadcasting Disruption Protection', 'Media'),
(37, 200000.00, 500000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Protects unreleased films, music, and manuscripts from leaks.', 12, TRUE, 'Media Intellectual Property Shield', 'Media'),
(38, 90000.00, 150000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Secures communication channels for investigative journalism.', 12, TRUE, 'Journalist Source Protection', 'Media'),
(39, 70000.00, 100000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Protects official brand accounts from being hacked or defaced.', 12, TRUE, 'Social Media Defacement Plan', 'Media'),
(40, 150000.00, 350000000.00, TIMESTAMP '2026-03-10 14:18:50.409493', 'Secures streaming services and digital content delivery.', 12, TRUE, 'Digital Content Platform Security', 'Media'),
(65, 20000000.00, 18000000.00, TIMESTAMP '2026-03-10 23:48:37.251889', '', 12, TRUE, 'Customer Data Protection', 'Banking'),
(66, 20000000.00, 18000000.00, TIMESTAMP '2026-03-10 23:48:37.903247', '', 12, TRUE, 'Customer Data Protection', 'Banking'),
(127, 200000.00, 200000.00, TIMESTAMP '2026-03-13 12:14:23.686968', '', 12, TRUE, 'Financial Data Protection Plan', 'IT / SaaS'); 
CREATE CACHED TABLE "PUBLIC"."INCIDENT_DOCUMENTS"(
    "INCIDENT_ID" BIGINT NOT NULL,
    "DOCUMENT_PATH" CHARACTER VARYING(255)
);        
-- 3 +/- SELECT COUNT(*) FROM PUBLIC.INCIDENT_DOCUMENTS;      
INSERT INTO "PUBLIC"."INCIDENT_DOCUMENTS" VALUES
(1, 'ransom_note.txt'),
(1, 'system_logs.zip'),
(1, 'forensic_report_v1.pdf');            
CREATE CACHED TABLE "PUBLIC"."INCIDENT_REPORT"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 120) NOT NULL,
    "DESCRIPTION" CHARACTER VARYING(2000),
    "ESTIMATED_LOSS_AMOUNT" NUMERIC(38, 2),
    "INCIDENT_TYPE" CHARACTER VARYING(255),
    "REPORTED_AT" TIMESTAMP(6),
    "STATUS" ENUM('REPORTED', 'RESOLVED', 'UNDER_INVESTIGATION'),
    "CUSTOMER_USER_ID" BIGINT,
    "SUBSCRIPTION_ID" BIGINT
);        
ALTER TABLE "PUBLIC"."INCIDENT_REPORT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_E" PRIMARY KEY("ID");              
-- 9 +/- SELECT COUNT(*) FROM PUBLIC.INCIDENT_REPORT;         
INSERT INTO "PUBLIC"."INCIDENT_REPORT" VALUES
(1, 'Servers encrypted by unknown payload deployed via an unpatched VPN vulnerability. Estimated 48-hour downtime.', 250000.00, 'Ransomware', TIMESTAMP '2026-03-05 14:18:50.886525', 'REPORTED', 2, 1),
(2, 'Patient medical records (2,500) exposed via unsecured API endpoint. Misconfiguration deployed March 1, detected March 3.', 500000.00, 'Data Breach', TIMESTAMP '2026-02-08 14:18:51.375253', 'REPORTED', 3, 2),
(3, 'Staff member clicked malicious link from spoofed admin email, exposing VPN credentials used to access patient scheduling system.', 180000.00, 'Phishing Attack', TIMESTAMP '2026-03-05 14:18:51.38255', 'UNDER_INVESTIGATION', 3, 2),
(4, 'CEO impersonation phishing led to unauthorized wire transfer of Rs.8,00,000 to a fraudulent account. Detected within 6 hours, bank freeze requested.', 800000.00, 'Phishing Attack', TIMESTAMP '2026-03-02 14:18:51.428315', 'UNDER_INVESTIGATION', 4, 3),
(33, 'Code Ddos Attack', 200000.00, 'DDoS', TIMESTAMP '2026-03-11 01:03:45.897372', 'REPORTED', 2, 33),
(65, U&'An internal employee with authorized access attempted to download sensitive company data from the internal database without proper authorization. The activity was detected through unusual access patterns and large data transfer attempts during non-working hours.\000aThe affected systems include the internal customer records database and the document management server. Immediate action was taken by the IT security team to revoke the employee''s access and isolate the affected systems.A security investigation is currently ongoing to determine the extent of the data exposure. Preliminary analysis indicates that a portion of confidential client information may have been accessed. Further forensic analysis and system audits are being conducted to assess the full impact.', 5000000.00, 'Insider Threat', TIMESTAMP '2026-03-11 11:57:54.799796', 'REPORTED', 2, 97),
(66, 'An internal employee with authorized access attempted to download sensitive company data from the internal database without proper authorization. The activity was detected through unusual access patterns and large data transfer attempts during non-working hours.', 20000000.00, 'Data Breach', TIMESTAMP '2026-03-11 12:02:39.41464', 'REPORTED', 2, 97),
(111, 'Cyber threat i.e:Data and important secure files got leaked ', 200000.00, 'Phishing', TIMESTAMP '2026-03-13 06:12:09.375696', 'REPORTED', 2, 97),
(112, 'Codedefense', 2000000.00, 'Ransomware', TIMESTAMP '2026-03-13 12:04:28.000672', 'REPORTED', 2, 33); 
CREATE CACHED TABLE "PUBLIC"."POLICY_APPLICABLE_TO"(
    "POLICY_ID" BIGINT NOT NULL,
    "INDUSTRY_TYPE" CHARACTER VARYING(255)
);        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.POLICY_APPLICABLE_TO;    
CREATE CACHED TABLE "PUBLIC"."POLICY_BENEFITS"(
    "POLICY_ID" BIGINT NOT NULL,
    "BENEFIT" CHARACTER VARYING(255)
);   
-- 126 +/- SELECT COUNT(*) FROM PUBLIC.POLICY_BENEFITS;       
INSERT INTO "PUBLIC"."POLICY_BENEFITS" VALUES
(1, 'Data breach response'),
(1, 'Customer notification costs'),
(1, 'Legal defense coverage'),
(1, 'Credit monitoring for customers'),
(2, 'ATM malware protection'),
(2, 'ATM fraud monitoring'),
(2, 'Transaction data recovery'),
(2, 'Incident investigation'),
(3, 'Payment gateway protection'),
(3, 'Fraud chargeback coverage'),
(3, 'Digital wallet security'),
(4, 'Ransomware protection'),
(4, 'System downtime compensation'),
(4, 'IT forensics'),
(5, 'Insider threat coverage'),
(5, 'Phishing protection'),
(5, 'Regulatory fine coverage'),
(6, 'Patient record breach coverage'),
(6, 'Medical data recovery'),
(6, 'Legal liability coverage'),
(6, 'Compliance support'),
(7, 'Video feed encryption failure'),
(7, 'Remote device hacking'),
(7, 'Patient privacy defense'),
(8, 'Pacemaker/Monitor hacking'),
(8, 'Device network isolation failure'),
(8, 'Ransomware on medical devices'),
(9, 'Ransom payment coverage'),
(9, 'Emergency patient transfer costs'),
(9, 'System rebuild expenses'),
(10, 'Prescription fraud'),
(10, 'Customer data theft'),
(10, 'Compliance fines'),
(11, 'Customer data protection'),
(11, 'Payment fraud coverage'),
(11, 'Website attack protection'),
(12, 'Downtime revenue loss'),
(12, 'Server overload recovery'),
(12, 'Traffic filtering costs'),
(13, 'Vendor breach liability'),
(13, 'Supply chain disruption'),
(13, 'Inventory system hacking'),
(14, 'Account takeover remediation'),
(14, 'Loyalty point fraud'),
(14, 'Password reset handling'),
(15, 'App vulnerabilities'),
(15, 'Mobile payment fraud'),
(15, 'Fake app takedown'),
(16, 'Software failure liability'),
(16, 'Client data breach protection'),
(16, 'Legal claims coverage'),
(17, 'SLA breach compensation'),
(17, 'Cloud provider dispute costs'),
(17, 'Data loss recovery'),
(18, 'Zero-day exploit recovery'),
(18, 'Patch deployment costs'),
(18, 'Client notification'),
(19, 'Multi-tenant breach'),
(19, 'Remote access hacking'),
(19, 'Client liability'),
(20, 'Model theft'),
(20, 'Data poisoning recovery'),
(20, 'Algorithmic bias defense'),
(21, 'Protection against industrial cyber attacks'),
(21, 'Production system recovery'),
(21, 'ICS malware protection'),
(22, 'Supplier breach'),
(22, 'Production halt loss'),
(22, 'Alternative sourcing costs'),
(23, 'Design theft'),
(23, 'Patent infringement defense'),
(23, 'Espionage tracking'),
(24, 'Robotics hacking'),
(24, 'Equipment damage repair'),
(24, 'Safety hazard liability'),
(25, 'Sensor spoofing'),
(25, 'Network isolation'),
(25, 'Data corruption'),
(26, 'FERPA compliance'),
(26, 'Student data breach'),
(26, 'Identity theft protection'),
(27, 'Malware containment'),
(27, 'Student device isolation'),
(27, 'Network rebuild'),
(28, 'Exam cheating rings'),
(28, 'Platform downtime'),
(28, 'Video bombing prevention'),
(29, 'Research theft'),
(29, 'Grant compliance'),
(29, 'Data destruction recovery'),
(30, 'Tuition fraud'),
(30, 'Payroll diversion'),
(30, 'Payment gateway hacking'),
(31, 'Public record breach'),
(31, 'Citizen notification'),
(31, 'Identity protection services'),
(32, 'Utility hacking'),
(32, 'Terrorist cyber attack'),
(32, 'Emergency response coordination'),
(33, 'Tax fraud'),
(33, 'Portal defacement'),
(33, 'Service denial recovery'),
(34, 'Espionage'),
(34, 'Insider threat'),
(34, 'Classified leak containment'),
(35, 'Ransom negotiation'),
(35, 'City service restoration'),
(35, 'Public communication'),
(36, 'Signal hijacking'),
(36, 'Advertising revenue loss'),
(36, 'Equipment repair'),
(37, 'Pre-release leak'),
(37, 'Copyright enforcement'),
(37, 'Piracy tracing'),
(38, 'Source unmasking'),
(38, 'Secure drop hacking'),
(38, 'Legal defense'),
(39, 'Account recovery'),
(39, 'PR crisis management'),
(39, 'Follower loss compensation'),
(40, 'Streaming piracy'),
(40, 'Subscriber data breach'),
(40, 'CDN hijacking'),
(65, 'Customer Data Loss'),
(66, 'Customer Data Loss'),
(127, 'Data breaches');         
CREATE CACHED TABLE "PUBLIC"."POLICY_SUBSCRIPTIONS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 163) NOT NULL,
    "APPROVED_AT" TIMESTAMP(6),
    "CALCULATED_PREMIUM" NUMERIC(38, 2),
    "COVERAGE_AMOUNT" NUMERIC(38, 2),
    "CREATED_AT" TIMESTAMP(6),
    "DEDUCTIBLE" NUMERIC(38, 2),
    "END_DATE" DATE,
    "EXCLUSIONS" CHARACTER VARYING(2000),
    "POLICY_LIMIT" NUMERIC(38, 2),
    "REJECTION_REASON" CHARACTER VARYING(2000),
    "RISK_SCORE" INTEGER,
    "START_DATE" DATE,
    "STATUS" ENUM('ACTIVE', 'APPROVED', 'PENDING', 'PENDING_PAYMENT', 'REJECTED'),
    "TENURE_MONTHS" INTEGER,
    "UNDERWRITER_NOTES" CHARACTER VARYING(2000),
    "APPROVED_BY" BIGINT,
    "ASSIGNED_UNDERWRITER_ID" BIGINT,
    "CUSTOMER_ID" BIGINT NOT NULL,
    "POLICY_ID" BIGINT NOT NULL,
    "RISK_ASSESSMENT_ID" BIGINT NOT NULL
);        
ALTER TABLE "PUBLIC"."POLICY_SUBSCRIPTIONS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("ID");         
-- 11 +/- SELECT COUNT(*) FROM PUBLIC.POLICY_SUBSCRIPTIONS;   
INSERT INTO "PUBLIC"."POLICY_SUBSCRIPTIONS" VALUES
(1, NULL, 200000.00, NULL, NULL, 50000.00, DATE '2027-02-10', '1. Damage caused by internal hardware failure. 2. Intentional data destruction by directors. 3. Incidents involving crypto-mining.', 400000000.00, NULL, NULL, DATE '2026-02-08', 'ACTIVE', NULL, NULL, NULL, NULL, 2, 16, 1),
(2, NULL, 135000.00, NULL, TIMESTAMP '2026-01-09 14:18:51.045359', 25000.00, DATE '2027-01-24', 'Pre-existing breaches. Incidents arising from unpatched systems older than 6 months.', 200000000.00, NULL, NULL, DATE '2026-01-24', 'ACTIVE', NULL, NULL, NULL, 6, 3, 6, 2),
(3, TIMESTAMP '2026-03-11 11:14:37.341142', 425000.00, 300000000.00, TIMESTAMP '2026-03-10 02:18:51.170318', 63750.00, NULL, 'Standard exclusions apply. PLUS: Social Engineering Fraud, Ransomware Payments (unless strictly authorized), and Cryptojacking are EXCLUDED.', 240000000.00, 'Risk is too high and cant trust', NULL, NULL, 'REJECTED', 12, '', 6, 6, 4, 1, 3),
(4, NULL, 92000.00, NULL, TIMESTAMP '2026-02-28 14:18:51.275754', 15000.00, DATE '2027-03-10', 'Social engineering attacks where no phishing training was completed.', 100000000.00, NULL, NULL, DATE '2026-03-10', 'PENDING_PAYMENT', NULL, 'Application assessed. Risk score 40 (LOW). Approved with standard deductible. Customer to complete payment within 7 days to activate policy.', NULL, 7, 5, 26, 4),
(33, TIMESTAMP '2026-03-11 01:02:35.010938', 234000.00, 280000000.00, TIMESTAMP '2026-03-11 00:48:50.734571', 23400.00, DATE '2028-03-11', 'Standard exclusions apply. Note: Coverage for Social Engineering is limited.', 224000000.00, NULL, NULL, DATE '2026-03-11', 'ACTIVE', 24, '', 6, 6, 2, 18, 33),
(65, TIMESTAMP '2026-03-11 11:33:35.505189', 153000.00, 90000000.00, TIMESTAMP '2026-03-11 09:35:58.661061', 22950.00, NULL, 'Standard exclusions apply. PLUS: Social Engineering Fraud, Ransomware Payments (unless strictly authorized), and Cryptojacking are EXCLUDED.', 72000000.00, 'No security controls and no supporting documents', NULL, NULL, 'REJECTED', 12, '', 9, 9, 3, 7, 65),
(66, TIMESTAMP '2026-03-11 11:08:57.17779', 136000.00, 60000000.00, TIMESTAMP '2026-03-11 09:37:11.935501', 20400.00, DATE '2027-03-11', 'Standard exclusions apply. PLUS: Social Engineering Fraud, Ransomware Payments (unless strictly authorized), and Cryptojacking are EXCLUDED.', 48000000.00, NULL, NULL, DATE '2026-03-11', 'ACTIVE', 12, '', 6, 6, 3, 10, 66),
(67, TIMESTAMP '2026-03-11 11:13:59.845572', 80000.00, 100000000.00, TIMESTAMP '2026-03-11 09:40:34.807297', 4000.00, DATE '2027-03-11', 'Standard policy exclusions apply.', 80000000.00, NULL, NULL, DATE '2026-03-11', 'ACTIVE', 12, '', 6, 6, 3, 10, 67),
(97, TIMESTAMP '2026-03-11 11:54:48.126864', 390000.00, 480000000.00, TIMESTAMP '2026-03-11 11:53:31.731425', 39000.00, DATE '2027-03-11', 'Standard exclusions apply. Note: Coverage for Social Engineering is limited.', 384000000.00, NULL, NULL, DATE '2026-03-11', 'ACTIVE', 12, '', 6, 6, 2, 19, 97),
(151, TIMESTAMP '2026-03-13 06:10:20.213928', 306000.00, 210000000.00, TIMESTAMP '2026-03-13 06:08:42.567409', 45900.00, NULL, 'Standard exclusions apply. PLUS: Social Engineering Fraud, Ransomware Payments (unless strictly authorized), and Cryptojacking are EXCLUDED.', 168000000.00, NULL, NULL, NULL, 'PENDING_PAYMENT', 12, '', 6, 6, 2, 18, 157),
(152, TIMESTAMP '2026-03-13 12:03:24.362811', 325000.00, 400000000.00, TIMESTAMP '2026-03-13 12:01:18.609712', 32500.00, DATE '2027-03-13', 'Standard exclusions apply. Note: Coverage for Social Engineering is limited.', 320000000.00, NULL, NULL, DATE '2026-03-13', 'ACTIVE', 12, '', 6, 6, 2, 17, 158);             
CREATE CACHED TABLE "PUBLIC"."RISK_ASSESSMENTS"(
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 170) NOT NULL,
    "ANNUAL_REVENUE" FLOAT(53),
    "BACKUP_AVAILABLE" BOOLEAN,
    "CREATED_AT" TIMESTAMP(6),
    "EMPLOYEE_COUNT" INTEGER,
    "ENCRYPTION_ENABLED" BOOLEAN,
    "FIREWALL_ENABLED" BOOLEAN,
    "HAS_DATA_PRIVACY_OFFICER" BOOLEAN,
    "ISO27001_CERTIFIED" BOOLEAN,
    "MFA_ENABLED" BOOLEAN,
    "PREVIOUS_INCIDENT_COUNT" INTEGER,
    "PROOF_DOCUMENT_PATHS" CHARACTER VARYING(2000),
    "RISK_LEVEL" CHARACTER VARYING(255),
    "RISK_SCORE" INTEGER,
    "CUSTOMER_ID" BIGINT NOT NULL
);             
ALTER TABLE "PUBLIC"."RISK_ASSESSMENTS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_A" PRIMARY KEY("ID");             
-- 11 +/- SELECT COUNT(*) FROM PUBLIC.RISK_ASSESSMENTS;       
INSERT INTO "PUBLIC"."RISK_ASSESSMENTS" VALUES
(1, 1.0E7, TRUE, TIMESTAMP '2026-02-03 14:18:50.870748', 150, TRUE, TRUE, NULL, NULL, TRUE, NULL, NULL, 'LOW', 35, 2),
(2, 5000000.0, TRUE, TIMESTAMP '2026-01-09 14:18:51.041289', 45, FALSE, TRUE, NULL, FALSE, FALSE, 1, NULL, 'MEDIUM', 52, 3),
(3, 5.0E8, TRUE, TIMESTAMP '2026-03-07 14:18:51.163983', 350, TRUE, TRUE, TRUE, TRUE, TRUE, 0, NULL, 'HIGH', 90, 4),
(4, 8000000.0, FALSE, TIMESTAMP '2026-02-28 14:18:51.271448', 80, TRUE, TRUE, NULL, NULL, TRUE, NULL, NULL, 'LOW', 40, 5),
(33, 500000.0, TRUE, TIMESTAMP '2026-03-11 00:48:49.962906', 100, TRUE, TRUE, TRUE, TRUE, TRUE, 1, 'uploads/proofs/2/1773170329790_FIREWALL_PROOF_Firewall report.pdf,uploads/proofs/2/1773170329907_ENCRYPTION_PROOF_Data Encryption Standard (DES) Certificate.pdf,uploads/proofs/2/1773170329915_BACKUP_PROOF_Backup & Disaster Recovery (DR) Compliance.pdf,uploads/proofs/2/1773170329922_MFA_PROOF_Identity & Access Management (IAM) Policy.pdf,uploads/proofs/2/1773170329932_ISO27001_PROOF_ISO 27001 ISMS Conformity Statement.pdf,uploads/proofs/2/1773170329941_DPO_PROOF_Appointment of Data Protection Officer (DPO).pdf,uploads/proofs/2/1773170329949_ADDITIONAL_Identity & Access Management (IAM) Policy.pdf', 'MEDIUM', 60, 2),
(65, 5000000.0, FALSE, TIMESTAMP '2026-03-11 09:35:57.612647', 50, FALSE, FALSE, FALSE, FALSE, FALSE, 1, NULL, 'HIGH', 90, 3),
(66, 5000000.0, FALSE, TIMESTAMP '2026-03-11 09:37:11.917228', 50, FALSE, FALSE, FALSE, FALSE, FALSE, 0, NULL, 'HIGH', 80, 3),
(67, 5000000.0, FALSE, TIMESTAMP '2026-03-11 09:40:34.545491', 50, FALSE, FALSE, FALSE, FALSE, FALSE, 0, NULL, 'LOW', 20, 3),
(97, 5000000.0, TRUE, TIMESTAMP '2026-03-11 11:53:31.420968', 50, TRUE, TRUE, TRUE, TRUE, TRUE, 0, 'uploads/proofs/2/1773210211200_FIREWALL_PROOF_Firewall report.pdf,uploads/proofs/2/1773210211385_ENCRYPTION_PROOF_Backup & Disaster Recovery (DR) Compliance.pdf,uploads/proofs/2/1773210211391_ISO27001_PROOF_Backup & Disaster Recovery (DR) Compliance.pdf,uploads/proofs/2/1773210211395_DPO_PROOF_ISO 27001 ISMS Conformity Statement.pdf,uploads/proofs/2/1773210211402_MFA_PROOF_Identity & Access Management (IAM) Policy.pdf,uploads/proofs/2/1773210211413_BACKUP_PROOF_Backup & Disaster Recovery (DR) Compliance.pdf', 'MEDIUM', 60, 2),
(157, 5000000.0, TRUE, TIMESTAMP '2026-03-13 06:08:42.216992', 50, TRUE, TRUE, TRUE, TRUE, TRUE, 0, 'uploads/proofs/2/1773362322098_FIREWALL_PROOF_Firewall report.pdf,uploads/proofs/2/1773362322184_ENCRYPTION_PROOF_Data Encryption Standard (DES) Certificate.pdf,uploads/proofs/2/1773362322193_BACKUP_PROOF_Backup & Disaster Recovery (DR) Compliance.pdf,uploads/proofs/2/1773362322200_MFA_PROOF_Identity & Access Management (IAM) Policy.pdf,uploads/proofs/2/1773362322204_ISO27001_PROOF_ISO 27001 ISMS Conformity Statement.pdf,uploads/proofs/2/1773362322213_DPO_PROOF_Data Encryption Standard (DES) Certificate.pdf', 'HIGH', 90, 2),
(158, 5000000.0, TRUE, TIMESTAMP '2026-03-13 12:01:17.997973', 100, TRUE, TRUE, TRUE, TRUE, TRUE, 2, 'uploads/proofs/2/1773383477823_FIREWALL_PROOF_Firewall report.pdf,uploads/proofs/2/1773383477941_ENCRYPTION_PROOF_Data Encryption Standard (DES) Certificate.pdf,uploads/proofs/2/1773383477953_BACKUP_PROOF_Backup & Disaster Recovery (DR) Compliance.pdf,uploads/proofs/2/1773383477965_MFA_PROOF_Backup & Disaster Recovery (DR) Compliance.pdf,uploads/proofs/2/1773383477976_ISO27001_PROOF_ISO 27001 ISMS Conformity Statement.pdf,uploads/proofs/2/1773383477989_DPO_PROOF_Data Encryption Standard (DES) Certificate.pdf', 'MEDIUM', 50, 2);     
CREATE CACHED TABLE "PUBLIC"."ROLES"(
    "ROLE_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 41) NOT NULL,
    "IS_ACTIVE" BOOLEAN,
    "ROLE_DESCRIPTION" CHARACTER VARYING(255),
    "ROLE_NAME" CHARACTER VARYING(255)
);    
ALTER TABLE "PUBLIC"."ROLES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ROLE_ID");   
-- 4 +/- SELECT COUNT(*) FROM PUBLIC.ROLES;   
INSERT INTO "PUBLIC"."ROLES" VALUES
(1, TRUE, 'System Administrator', 'ROLE_ADMIN'),
(2, TRUE, 'Customer User', 'ROLE_CUSTOMER'),
(3, TRUE, 'Policy Approval Officer', 'ROLE_UNDERWRITER'),
(4, TRUE, 'Claims Processing Officer', 'ROLE_CLAIMS_OFFICER');
CREATE CACHED TABLE "PUBLIC"."USERS"(
    "USER_ID" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1 RESTART WITH 152) NOT NULL,
    "ACCOUNT_STATUS" CHARACTER VARYING(255),
    "ANNUAL_REVENUE" CHARACTER VARYING(255),
    "COMPANY_ADDRESS" CHARACTER VARYING(255),
    "COMPANY_NAME" CHARACTER VARYING(255),
    "COMPANY_SIZE" CHARACTER VARYING(255),
    "COMPANY_WEBSITE" CHARACTER VARYING(255),
    "CREATED_AT" TIMESTAMP(6),
    "EMAIL" CHARACTER VARYING(255) NOT NULL,
    "FULL_NAME" CHARACTER VARYING(255) NOT NULL,
    "INDUSTRY" CHARACTER VARYING(255),
    "PASSWORD_HASH" CHARACTER VARYING(255) NOT NULL,
    "PHONE_NUMBER" CHARACTER VARYING(255),
    "REGISTRATION_NUMBER" CHARACTER VARYING(255),
    "UPDATED_AT" TIMESTAMP(6),
    "ROLE_ID" BIGINT NOT NULL
);       
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4D" PRIMARY KEY("USER_ID");  
-- 11 +/- SELECT COUNT(*) FROM PUBLIC.USERS;  
INSERT INTO "PUBLIC"."USERS" VALUES
(1, 'ACTIVE', NULL, NULL, 'CyberAssure Platform', NULL, NULL, TIMESTAMP '2026-03-10 14:18:49.303961', 'admin@cyberassure.com', 'System Administrator', NULL, '$2a$10$lo9eA279WPL5h44TbOj9Eu3s/aM.CB8HtnCOlt7jQCLaJOEWKYNW2', '9999999999', NULL, NULL, 1),
(2, 'ACTIVE', '10000000', '123 Tech Park, Bangalore', 'TechCorp India', 'Medium (50-250)', 'https://techcorp.in', TIMESTAMP '2026-03-10 14:18:49.468919', 'rajesh@techcorp.in', 'Rajesh Kumar', 'IT / SaaS', '$2a$10$8FzdmKPl/4oLk91ZnfJHfugExhUNf.k9uK/AvoQsqmhfwaMtnsNS.', '9876543210', 'CIN-U72900KA2020PTC123456', NULL, 2),
(3, 'ACTIVE', NULL, NULL, 'Global Health Clinics', 'Small (1-50)', NULL, TIMESTAMP '2026-03-10 14:18:49.595928', 'priya@globalhealth.in', 'Priya Sharma', 'Healthcare', '$2a$10$4U9.rlHN9bcQdil5B/iky.weydeU1lXDxVIFGSROSJNPqnhkHhd02', '9123456780', NULL, NULL, 2),
(4, 'ACTIVE', NULL, NULL, 'FinSecure Bank', 'Large (250+)', NULL, TIMESTAMP '2026-03-10 14:18:49.71991', 'amit@finsecure.in', 'Amit Patel', 'Banking', '$2a$10$WT/HNKw6jWCRftPjGJiTWOrcfkBkf2TyhKwvJQFeK4W02psdOJjuW', '9988776655', NULL, NULL, 2),
(5, 'ACTIVE', NULL, NULL, 'EduTech Solutions', 'Medium (50-250)', NULL, TIMESTAMP '2026-03-10 14:18:49.829962', 'sneha@edutech.in', 'Sneha Gupta', 'Education', '$2a$10$PsuxmzupjXbzSOKQC/o1xOlXdo7sxhWejt.xEfVtau0ZiQ4lX/ZyK', '9876501234', NULL, NULL, 2),
(6, 'ACTIVE', NULL, NULL, 'CyberAssure Internal', NULL, NULL, TIMESTAMP '2026-03-10 14:18:49.961301', 'vikram@cyberassure.in', 'Vikram Singh', NULL, '$2a$10$Mhuwwty300vQw7pLalnHDuKlfj5sOLiVIBTsXpOO.hf4jKvJOKEWO', '9112223333', NULL, NULL, 3),
(7, 'ACTIVE', NULL, NULL, 'CyberAssure Internal', NULL, NULL, TIMESTAMP '2026-03-10 14:18:50.071841', 'neha@cyberassure.in', 'Neha Verma', NULL, '$2a$10$JZ4JaUteCLHoxuQq0ZvXZe.eZ/4dI3YOxbo8tLJ4IHwKkcaWDWdP6', '9223334444', NULL, NULL, 3),
(8, 'ACTIVE', NULL, NULL, 'CyberAssure Internal', NULL, NULL, TIMESTAMP '2026-03-10 14:18:50.20931', 'arjun@cyberassure.in', 'Arjun Desai', NULL, '$2a$10$k4PjI6XeNeaKwnQR1.Wlyem6CeY/JK/TvGcdHxZDLo/RDDWNeVQ3.', '9334445555', NULL, NULL, 4),
(9, 'ACTIVE', NULL, NULL, 'CyberAssure Internal', NULL, NULL, TIMESTAMP '2026-03-10 14:18:50.375446', 'meera@cyberassure.in', 'Meera Reddy', NULL, '$2a$10$aceeMY1xpA7Z8d98jowaLukLFbbcFWTfeuFz6Vdtxb.XBFa7UKdGe', '9445556666', NULL, NULL, 3),
(33, 'ACTIVE', NULL, NULL, 'CyberAssure Internal', NULL, NULL, TIMESTAMP '2026-03-10 22:48:47.597976', 'spoorthymudragada@gmail.com', 'Spoorthy', NULL, '$2a$10$okKwtu1E9qspNvZcUfMGp./m5zgjXNbLgNG8FZoaQzNYTqEY7zA5G', 'NA', NULL, NULL, 4),
(127, 'ACTIVE', U&'\20b910 Crore - \20b950 Crore', 'New York', 'Acme Tech Limited', U&'51\2013200 employees', 'https://acme.com', TIMESTAMP '2026-03-13 10:39:45.247979', 'krishna@gmail.com', 'Krishna', 'IT / SaaS', '$2a$10$RmsXfZu0803RRJUc1KsKouYr3LDHbqT1Frki9MP1axbNv8GUtjD.S', '7670836092', '200560', NULL, 2);
ALTER TABLE "PUBLIC"."ROLES" ADD CONSTRAINT "PUBLIC"."UK716HGXP60YM1LIFRDGP67XT5K" UNIQUE NULLS DISTINCT ("ROLE_NAME");       
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."UK6DOTKOTT2KJSP8VW4D0M25FB7" UNIQUE NULLS DISTINCT ("EMAIL");           
ALTER TABLE "PUBLIC"."RISK_ASSESSMENTS" ADD CONSTRAINT "PUBLIC"."FKRLL2DKI9G1DLFTBMKYQBCXOYW" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;      
ALTER TABLE "PUBLIC"."POLICY_SUBSCRIPTIONS" ADD CONSTRAINT "PUBLIC"."FKH1SA1HUWAKFLHWDVMGATQG6SY" FOREIGN KEY("CUSTOMER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;  
ALTER TABLE "PUBLIC"."CLAIM" ADD CONSTRAINT "PUBLIC"."FKONOMPUMYUAAXMM7E33BTKUE3V" FOREIGN KEY("INCIDENT_ID") REFERENCES "PUBLIC"."INCIDENT_REPORT"("ID") NOCHECK;            
ALTER TABLE "PUBLIC"."INCIDENT_DOCUMENTS" ADD CONSTRAINT "PUBLIC"."FKH4PP2UU51QK4UFPOTCE3R28G7" FOREIGN KEY("INCIDENT_ID") REFERENCES "PUBLIC"."INCIDENT_REPORT"("ID") NOCHECK;               
ALTER TABLE "PUBLIC"."POLICY_SUBSCRIPTIONS" ADD CONSTRAINT "PUBLIC"."FK6SHEARMXPMBADFC4E67944IU0" FOREIGN KEY("RISK_ASSESSMENT_ID") REFERENCES "PUBLIC"."RISK_ASSESSMENTS"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."INCIDENT_REPORT" ADD CONSTRAINT "PUBLIC"."FK2N8STVUWIOC43XCU332PX3E84" FOREIGN KEY("SUBSCRIPTION_ID") REFERENCES "PUBLIC"."POLICY_SUBSCRIPTIONS"("ID") NOCHECK;         
ALTER TABLE "PUBLIC"."INCIDENT_REPORT" ADD CONSTRAINT "PUBLIC"."FKIRPPCTBQ52JOLM3DGF0X3VD1L" FOREIGN KEY("CUSTOMER_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;  
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."FKP56C1712K691LHSYEWCSSF40F" FOREIGN KEY("ROLE_ID") REFERENCES "PUBLIC"."ROLES"("ROLE_ID") NOCHECK;     
ALTER TABLE "PUBLIC"."POLICY_SUBSCRIPTIONS" ADD CONSTRAINT "PUBLIC"."FK2XBD61NGXB5Y1L7E86QP9MI6J" FOREIGN KEY("APPROVED_BY") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;  
ALTER TABLE "PUBLIC"."POLICY_SUBSCRIPTIONS" ADD CONSTRAINT "PUBLIC"."FK95VF9JJM5SM484O96287EPAL2" FOREIGN KEY("ASSIGNED_UNDERWRITER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;      
ALTER TABLE "PUBLIC"."CLAIM" ADD CONSTRAINT "PUBLIC"."FK6XWWVNSSF8P59148MAP81UXIR" FOREIGN KEY("REVIEWED_BY_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;         
ALTER TABLE "PUBLIC"."CLAIM" ADD CONSTRAINT "PUBLIC"."FKNR413RDTPU3OK0D1MYC57SCX9" FOREIGN KEY("CUSTOMER_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;            
ALTER TABLE "PUBLIC"."POLICY_SUBSCRIPTIONS" ADD CONSTRAINT "PUBLIC"."FKQ1N2KI8BLPEMFBS8CA101ALJ2" FOREIGN KEY("POLICY_ID") REFERENCES "PUBLIC"."CYBER_POLICIES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."POLICY_BENEFITS" ADD CONSTRAINT "PUBLIC"."FK49RXL0HRI09W3Q17UUHBD6A3R" FOREIGN KEY("POLICY_ID") REFERENCES "PUBLIC"."CYBER_POLICIES"("ID") NOCHECK;     
ALTER TABLE "PUBLIC"."POLICY_APPLICABLE_TO" ADD CONSTRAINT "PUBLIC"."FKN2YL1NWXLSEYM5RS8W6MOXFXP" FOREIGN KEY("POLICY_ID") REFERENCES "PUBLIC"."CYBER_POLICIES"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."CLAIM" ADD CONSTRAINT "PUBLIC"."FK2MFL7AFX1TW18XMOO4PNRCUG8" FOREIGN KEY("ASSIGNED_OFFICER_USER_ID") REFERENCES "PUBLIC"."USERS"("USER_ID") NOCHECK;    
